spring:
  application:
    name: response-caching-gateway
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
    reactor:
      netty:
        http:
          client: DEBUG